version: '3'

services:
  app:
    build: .
    entrypoint: ['.docker/entrypoint.sh']
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image: postgres
    # build: .docker/postgres
    container_name: db
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
